name: CI Workflow

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Python and pip versions
        run: |
          python --version
          pip --version

      - name: Activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Run Django migrations (if applicable)
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          python manage.py test

      - name: Deploy to main if tests pass
        if: success()
        run: |
          git config --global user.email "sarahbousta11@gmail.com"
          git config --global user.name "sarahbousta"
          git checkout main
          git merge --ff-only dev
          git push origin main